## variables
@email1 = artexi1464.2@gmail.com
@name = test
@password = helloWorld1234!!!

### 회원가입
POST http://localhost:8080/api/user
Content-Type: application/json

{
  "email": "{{email1}}",
  "name": "{{name}}",
  "password": "{{password}}"
}

### 이메일 인증 전 로그인
POST http://localhost:8080/api/auth/login
Content-Type: application/json

{
  "email": "{{email1}}",
  "password": "{{password}}"
}

> {%
    client.global.set("access_token", response.body.accessToken);
    client.global.set("refresh_token", response.body.refreshToken);
%}

###  이메일 인증
POST http://localhost:8080/api/user/email-verification
Content-Type: application/json

{
  "token": "6464d090-2ea7-4c01-a90e-ad090de3ca46"
}

