### password 에 특수문자 안들어감
POST http://localhost:8080/api/user
Content-Type: application/json

{
"email": "helloworld@gmail.com",
"name": "helloworld",
"password": "12341234"
}

### password 가 10 ~ 30 글자가 아님
POST http://localhost:8080/api/user
Content-Type: application/json

{
  "email": "helloworld11@gmail.com",
  "name": "helloworld",
  "password": "helloWorld1234!!!"
}

### 인증
POST http://localhost:8080/api/user/email-verification
Content-Type: application/json

{
  "token": "7ea7f9ee-8b92-41ec-9e59-9f5ca25ce834"
}
