### password 에 특수문자 안들어감
POST http://localhost:8080/api/user
Content-Type: application/json

{
"email": "helloworld@gmail.com",
"name": "helloworld",
"password": "12341234"
}

### password 가 10 ~ 30 글자가 아님
POST http://localhost:8080/api/user
Content-Type: application/json

{
  "email": "helloworld3@gmail.com",
  "name": "helloworld",
  "password": "helloWorld1234!!!"
}

### 인증
POST http://localhost:8080/api/user/email-verification
Content-Type: application/json

{
  "token": "d497abfe-2f37-4958-8741-730b7099857e"
}
