## variables
@email1 = helloworld@gmail.com
@email2 = foobar@gmail.com
@name = test
@password = helloWorld1234!!!

### 수정
PUT http://localhost:8080/api/post/{{post_id}}
Authorization: Bearer {{access_token}}
Content-Type: application/json

{
  "title": "updated title",
  "contents": "updated token"
}

### 다른 계정으로 수정 시도
POST http://localhost:8080/api/auth/login
Content-Type: application/json

{
  "email": "{{email2}}",
  "password": "{{password}}"
}
> {%
    client.global.set("access_token", response.body.accessToken);
    client.global.set("refresh_token", response.body.refreshToken);
%}

### 수정 실패
PUT http://localhost:8080/api/post/{{post_id}}
Authorization: Bearer {{access_token}}
Content-Type: application/json

{
  "title": "updated by another person",
  "contents": "updated token"
}
